version: "3"
services:
  what-if:
    container_name: what-if
    image: what-if:1.0
    build:
      context: ./docker
      dockerfile: ./what-if/Dockerfile
    volumes:
      - ./:/work
    working_dir: /work
    ports:
      - 8888:8888
    command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser --NotebookApp.token=''
